In [1]:
# import stuff we might need
# this notebook is for gathering other data for our analyses

import os
import sys
import csv
import math
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as stats

In [31]:
# Make a pandas df for age groups and registered drivers
# ignore first path, not putting it in github because we don't need most of the data
# I will output a more useful csv after I format it a little
csvpth = os.path.join("..", "agereg.csv")
agedf = pd.read_csv(csvpth)

# making a note that this csv is incredibly awful to look at

# there are some specified age groups I can grab
# column index + 2 has the total for that age group
# year 2015 is in index 55

ageDict = {"15-19" : agedf["Unnamed: 18"].iloc[55], "20-24" : agedf["Unnamed: 36"].iloc[55], "30-34" : agedf["Unnamed: 42"].iloc[55], 
          "25-29" : agedf["Unnamed: 39"].iloc[55], "35-39" : agedf["Unnamed: 45"].iloc[55], "40-44" : agedf["Unnamed: 48"].iloc[55], 
          "45-49" : agedf["Unnamed: 51"].iloc[55], "50-54" : agedf["Unnamed: 54"].iloc[55], "55-59" : agedf["Unnamed: 57"].iloc[55], 
          "60-64" : agedf["Unnamed: 60"].iloc[55], "65-69" : agedf["Unnamed: 63"].iloc[55], "70-74" : agedf["Unnamed: 66"].iloc[55], 
          "75-79" : agedf["Unnamed: 69"].iloc[55], "80-84" : agedf["Unnamed: 72"].iloc[55], "85+" : agedf["Unnamed: 75"].iloc[55]}
# ageDict has number of licensed drivers in 2015 by age group

agedf = pd.DataFrame(ageDict, index = list(ageDict.keys()))

,15-19,20-24,30-34,25-29,35-39,40-44,45-49,50-54,55-59,60-64,65-69,70-74,75-79,80-84,85+
15-19,"8,591","17,630","19,120","19,266","18,088","18,107","18,988","20,488","20,068","17,647","14,788","10,232","6,834","4,521","3,716"
20-24,"8,591","17,630","19,120","19,266","18,088","18,107","18,988","20,488","20,068","17,647","14,788","10,232","6,834","4,521","3,716"
30-34,"8,591","17,630","19,120","19,266","18,088","18,107","18,988","20,488","20,068","17,647","14,788","10,232","6,834","4,521","3,716"
25-29,"8,591","17,630","19,120","19,266","18,088","18,107","18,988","20,488","20,068","17,647","14,788","10,232","6,834","4,521","3,716"
35-39,"8,591","17,630","19,120","19,266","18,088","18,107","18,988","20,488","20,068","17,647","14,788","10,232","6,834","4,521","3,716"
40-44,"8,591","17,630","19,120","19,266","18,088","18,107","18,988","20,488","20,068","17,647","14,788","10,232","6,834","4,521","3,716"
45-49,"8,591","17,630","19,120","19,266","18,088","18,107","18,988","20,488","20,068","17,647","14,788","10,232","6,834","4,521","3,716"
50-54,"8,591","17,630","19,120","19,266","18,088","18,107","18,988","20,488","20,068","17,647","14,788","10,232","6,834","4,521","3,716"
55-59,"8,591","17,630","19,120","19,266","18,088","18,107","18,988","20,488","20,068","17,647","14,788","10,232","6,834","4,521","3,716"
60-64,"8,591","17,630","19,120","19,266","18,088","18,107","18,988","20,488","20,068","17,647","14,788","10,232","6,834","4,521","3,716"
65-69,"8,591","17,630","19,120","19,266","18,088","18,107","18,988","20,488","20,068","17,647","14,788","10,232","6,834","4,521","3,716"
70-74,"8,591","17,630","19,120","19,266","18,088","18,107","18,988","20,488","20,068","17,647","14,788","10,232","6,834","4,521","3,716"
75-79,"8,591","17,630","19,120","19,266","18,088","18,107","18,988","20,488","20,068","17,647","14,788","10,232","6,834","4,521","3,716"
80-84,"8,591","17,630","19,120","19,266","18,088","18,107","18,988","20,488","20,068","17,647","14,788","10,232","6,834","4,521","3,716"
85+,"8,591","17,630","19,120","19,266","18,088","18,107","18,988","20,488","20,068","17,647","14,788","10,232","6,834","4,521","3,716"

In [42]:
# Modify drivers by age csv to include number of crashes by age group
# Note that original csv was meant to be in thousands
agedf = pd.read_csv("licensed_drivers_by_age.csv", header = None)
agedf[1] = agedf[1].str.strip() + ",000"
agedf.rename(columns = {0 : "Age Group", 1 : "Licensed Drivers"}, inplace =True)

In [34]:
# Get crashes list and get age column
pth = os.path.join("FARS2015NationalCSV", "person.csv")
ages = pd.read_csv(pth)
#ages.head()
# Only care about ages and crashes
ages = ages["AGE"]

0    68
1    49
2    31
3    20
4    40
Name: AGE, dtype: int64

In [60]:
# crash number dictionary to gather number of crashes per age range
# dictionary comprehension
crashDict = dict((k,0) for k in list(agedf["Age Group"]))
crashDict("Trash") = 0

{'15-19': 0,
 '20-24': 0,
 '30-34': 0,
 '25-29': 0,
 '35-39': 0,
 '40-44': 0,
 '45-49': 0,
 '50-54': 0,
 '55-59': 0,
 '60-64': 0,
 '65-69': 0,
 '70-74': 0,
 '75-79': 0,
 '80-84': 0,
 '85+': 0}